# Generated by Django 5.0.7 on 2026-04-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('sector', models.CharField(choices=[('tech', 'Technology'), ('real_estate', 'Real Estate'), ('finance', 'Finance')], max_length=30)),
                ('year_acquired', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('exited', 'Exited'), ('pending', 'Pending')], default='active', max_length=20)),
                ('description', models.TextField()),
                ('headline_metric', models.CharField(help_text="E.g. '3× return', '$12M ARR'", max_length=200)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-year_acquired'],
            },
        ),
        migrations.CreateModel(
            name='SiteStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="E.g. 'Assets Under Management'", max_length=100)),
                ('value', models.CharField(help_text="E.g. '$240M'", max_length=50)),
                ('suffix', models.CharField(blank=True, help_text="E.g. 'M+' appended to counter", max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
