# Generated by Django 5.0.7 on 2026-06-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='sector',
            field=models.CharField(choices=[('real_estate', 'Real Estate'), ('fintech', 'Fintech'), ('finance', 'Finance')], max_length=30),
        ),
    ]
